companies_to_run = [
    "WHOOP",
    "Wise",
    "Wix",
    "Wiz",
    "Wonder",
    "Workato",
    "Workday",
    "Workiva",
    "Workrise",
    "Wrapbook",
    "X",
    "Yahoo",
    "Yelp",
    "Yotpo",
    "Yuga Labs",
    "Yugabyte",
    "Zapier",
    "Zebec",
    "ZenBusiness",
    "Zendesk",
    "Zenoti",
    "Zeta",
    "Zillow",
    "Zip",
    "Zocdoc",
    "Zoom Video Communications, Inc.",
    "ZoomInfo",
    "Zscaler",
    "Zynga",
]