companies = [
'Cruise',
'Waymo',
'Lineage Logistics',
'CloudKitchens',
'NYDIG',
'CoreWeave',
'OneStream Software',
'Sierra Space',
'Quantinuum',
'Ava Labs',
'Neuralink',
'Binance.US',
'AngelList',
'Inflection AI',
'InsightSoftware',
'Avride',
'Aptean',
'Wonder',
'Armis Security',
'Figure',
'Group14 Technologies',
'iCIMS',
'iFIT',
'Transmit Security',
'Ethos Life',
'Figure',
'Syniverse',
'VistaJet',
'Mavenir',
'Electrify America',
'1inch Limited',
'Recharge',
'Clear Street',
'Pivot Bio',
'Black Sesame Technologies',
'XtalPi',
'Aleph Holding',
'Saks.com',
'ISN Software',
'ShiftKey',
'Xpansiv',
'NinjaOne',
'Kindbody',
'BitGo',
'NantOmics',
'Ascend Elements',
'NMI',
'Perfect Day',
'Apollo GraphQL',
'Candy Digital',
'Runway',
'Lambda',
'Berachain',
'Zip',
'Figment',
'Dexterity',
'Wealthfront',
'LIQUiDITY Group',
'EverlyWell',
'Included Health',
'Hotel Engine',
'Zum',
'Mapbox',
'Keyfactor',
'Doc.com',
'Wilson Wolf Corporation',
'Cart.com',
'Triller',
'Sidewalk Infrastructure Partners',
'Together AI',
'Human Longevity',
'Iyuno-SDI',
'Form Energy',
'Our Next Energy',
'Lightmatter',
'Proteus Digital Health',
'Innovusion',
'HeadSpin',
'Replit',
'Alphaeon',
'KoBold Metals',
'Enable',
'Lendbuzz',
'Plenty',
'TeraWatt Infrastructure',
'Atmosphere',
'Colossal Biosciences',
'Adept AI',
'Headway',
'BFMeta',
'Ohmium',
'Avenue One',
'Gradiant',
'Restaurant365',
'VectorBuilder',
'Typeface',
'Imbue',
'Kin Insurance',
'Electric Hydrogen',
'Lyten',
'Prove',
'Metropolis',
'Rokid',
'MaintainX',
'Andalusia Labs',
'Vestwell',
'EmployerDirect Healthcare',
'Insitro',
'ElevenLabs',
'Bugcrowd',
'Polyhedra Network',
'Merkle Manufactory',
'LetsGetChecked',
'Stax',
'UST',
'Securonix',
'Plus',
'FLASH',
'Forward',
'Aqua Security',
'Forte',
'Jellysmack',
'Commonwealth Fusion',
'Resilience',
'OfferUp',
'Wisk Aero',
'FLYR Labs',
'Entrata',
'GoGuardian',
'Mark43',
'FabFitFun',
'Immunai',
'HealthCare.com',
'D2iq',
'TechStyle Fashion Group',
'Cadence Solutions',
'EcoFlow Tech',
'Sightline Payments',
'KKW Beauty',
'Verily',
'Fractal Analytics',
'InvestCloud',
'Emplifi',
'Kendra Scott Design',
'assembly',
'iSpot.tv',
'Semperis',
'Velocity Global',
'Ultima Genomics',
'MNTN',
'Tebra',
'Exterro',
'Prodege',
'TerraPower',
'Zynga',
'Zendesk',
'Slack'
]