name: Web Scraping

on:
  schedule:
    - cron: "0 5 * * *" # Run the job every day at midnight
  workflow_dispatch:

env:
  airtable_api_key: ${{ secrets.AIRTABLE_API_KEY }}

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "pip" #caching pip dependencies

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Web Scraping Job
        run: python run_scraper.py jobs
