name: Web Scraping

on:
  schedule:
    - cron: '27 7 * * *'   # Run the job every day at midnight
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  
jobs:
  scrape:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Use Airtable API Secret
        run: echo ${{ secrets.AIRTABLE_API_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Web Scraping Job
        run: python run_scrapper.py --jobs
        shell: bash
